controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drivr_controller:
      type: diff_drive_controller/DiffDriveController

forward_velocity_controller:
  ros__parameters:
    joints:
      - Ruota_destra_posteriore
      - Ruota_sinistra_anteriore
      - Ruota_destra_anteriore
      - Ruota_sinistra_posteriore
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

forward_position_controller:
  ros__parameters:
    joints:
      - Inclina_sinistra_anteriore
      - Inclina_destra_anteriore
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity


